
export default {
    DASHBOARD: 'ראשי',
    SETTINGS: 'הגדרות',
    SAVE_SETTINGS: 'שמור הגדרות',
    THEME: 'רקע',
    ADVANCED_SEARCH: 'חיפוש מתקדם',    
    STATUS: 'סטטוס',
    PRIORITY: 'עדיפות',
    LOCATION: 'מיקום',
    UPDATE_TIME: 'תאריך עדכון',
    SELECT_USER: 'בחר משתמש',
    SAVE: 'שמור',
    CANCEL: 'ביטול',
    SEARCH: 'חיפוש',
    CLEAR_FIELDS: 'נקה שדות',
    FROM_DATE: 'מתאריך',
    TO_DATE: 'עד תאריך',
    HISTORY: 'היסטוריה',
    USER: 'משתמש',
    ENTERANCE: 'כניסה למערכת',
    USERNAME: 'שם משתמש',
    PASSWORD: 'סיסמא',
    FORGOT_PASSWORD: 'שכחת סיסמא',
    IMAGE: 'תמונה',
    SELECT_FILE: 'בחר קובץ',
    FILE_TYPE_ERROR_MSG: 'סוג קובץ לא חוקי. ניתן לבחור קובץ מסוג JPEG, JPG, BMP, MP4, PNG',
    ERROR_UPLOAD_FILE: 'שגיאה בטעינת קובץ',
    ERROR_ACCURED: 'אירעה שגיאה',
    LOG_OUT: 'התנתקות',
    ENTER: 'כניסה',
    EXIT: 'יציאה',
    ADD: 'הוסף',
    NO_ITEMS_FOUND: 'לא נמצאו רשומות',
    UPDATE: 'עדכן',
    VERSION: 'גרסה',
    CHANGES_NOT_SAVED : 'לא בוצעו שינויים',
    BACK_TO_EDIT: 'חזרה לעריכה',
    APP_TITLE: 'ניטור מערכת',
    REPORTS: 'דוחות',
    HOME: 'דף ראשי',
};