// src/Config/TextEn.js
const TextEn = {
  DASHBOARD: "Dashboard",
  SETTINGS: "Settings",
  SAVE_SETTINGS: "Save Settings",
  THEME: "Theme",
  ADVANCED_SEARCH: "Advanced Search",
  STATUS: "Status",
  PRIORITY: "Priority",
  LOCATION: "Location",
  UPDATE_TIME: "Update Date",
  SELECT_USER: "Select User",
  SAVE: "Save",
  CANCEL: "Cancel",
  SEARCH: "Search",
  CLEAR_FIELDS: "Clear Fields",
  FROM_DATE: "From Date",
  TO_DATE: "To Date",
  HISTORY: "History",
  USER: "User",
  ENTERANCE: "Login",
  USERNAME: "Username",
  PASSWORD: "Password",
  FORGOT_PASSWORD: "Forgot Password",
  SEND: "Send",
  BACK_TO_LOGIN: "Back to Login",
  IMAGE: "Image",
  SELECT_FILE: "Select File",
  FILE_TYPE_ERROR_MSG:
    "Invalid file type. You can select a file of type JPEG, JPG, BMP, MP4, PNG",
  ERROR_UPLOAD_FILE: "Error uploading file",
  ERROR_ACCURED: "An error occurred",
  LOG_OUT: "Log Out",
  ENTER: "Enter",
  EXIT: "Exit",
  ADD: "Add",
  NO_ITEMS_FOUND: "No records found",
  UPDATE: "Update",
  VERSION: "Version",
  CHANGES_NOT_SAVED: "No changes were made",
  BACK_TO_EDIT: "Back to Edit",
  APP_TITLE: "System Reports",
  REPORTS: "Reports",
  HOME: "Home Page",
  ERR_INVALID_LOGIN: "Incorrect username or password.",
  ERR_REQUIRED_FIELDS: "Please fill in all required fields.",
  ERR_NO_TOKEN: "Login failed: no access token received.",
  LOADER_DATA : "Loading data...",
   GUEST : "Guest",
};

export default TextEn;
